### PR TITLE
docs: improve sidebar for the changelog page

### PR DESCRIPTION
**Pull request by tigarmo**
These two facts:

- Changelog entries for a given version can be rather long
- We order the versions "chronologically" instead of "numerically"

... mean that the entries for a given major version can get "hidden" further
down the page if multiple hotfixes have been released in the meantime. This
can cause confusion and make it seem like the version has not been released,
or at least doesn't have changelog entries. To alleviate this, add a table of
contents to the sidebar that links to the subsection for each release.

- [ ] Have you followed the [guidelines for contributing](https://github.com/canonical/snapcraft/blob/main/CONTRIBUTING.md)?
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `tox run -m lint`?
- [ ] Have you successfully run `tox run -e test-py310`? (supported versions: `py39`, `py310`, `py311`, `py312`)

-----

### CODE REVIEW

**Review by mr-cal — COMMENTED** [review]
What do you think about setting a max depth such that only the contents only show the top-level versions are shown and not the sub-headings?  I'm not sure if it's possible.

A few weeks ago, I tried to figure out how to do it on the right-hand page navigation (see attached) but gave up because I couldn't figure out how to do it without html/css hacking.

image

**Comment by tigarmo** [comment]
@mr-cal what a coincidence, I had the same thought and managed to find a way to do it (don't ask me how)
Looks like this now; I also updated the commit and will update the PR description
image

**Review by mr-cal — APPROVED** [review]
It's beautiful, thank you!!

> don't ask me how

I closed my eyes when approving so I wouldn't find out.

**Review by lengau — APPROVED** [review]

**Review by medubelko — APPROVED** [review]
`:tocdepth:` can't see you, `:tocdepth:` can't hurt you.

**Comment by mr-cal** [comment]
spread test failure is a launchpad connectivity issue, merging anyway

**Pull request merged**
