### PR TITLE
build(lint): use ruff from snap

### PR DESCRIPTION
**Pull request by lengau**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `tox run -m lint`?
- [x] Have you successfully run `tox run -e test-py310`? (supported versions: `py39`, `py310`, `py311`, `py312`)

-----

### CODE REVIEW

**Review by sergiusens — APPROVED** [review]
\o/

Now do pyright :-D

**Review by mr-cal — APPROVED** [review]

**Comment by lengau** [comment]
@sergiusens I would genuinely love to! My problem with pyright isn't that it's not a great IDE tool, but that release upgrades will suddenly break CI, which can derail work. Ruff has [a policy](https://docs.astral.sh/ruff/versioning/) that has so far prevented these issues, as we seldom have to make a PR to "satisfy ruff." As the app matures, I hope to set up major release channels as well so that we can upgrade to new major releases in a controlled manner.

Similarly stable tools that I'd be comfortable moving over to snap channels (assuming the snaps have regular releases and channels gating major verssions) include black, mypy, codespell and yamllint.

I've posted a [feature request](https://github.com/microsoft/pyright/issues/7315) for pyright to provide some level of stability. Even if pyright had less overall coverage in CI, as a trade-off for being able to consistently have the latest pyright I think it'd be well worth it.

**Comment by sergiusens** [comment]
I use pyright as my LSP :-)
I guess I should look into going back to the python backed one and use ruff
as an add-on to that.

**Comment by lengau** [comment]
Yeah I like it as an LSP. The CI breakage is the only real downside

**Pull request merged**
