### PR TITLE
Add jammy and x64 labels for self hosted runners.

### PR DESCRIPTION
**Pull request by codethulu**
- [ ] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `tox run -m lint`?
- [ ] Have you successfully run `tox run -e test-py310`? (supported versions: `py39`, `py310`, `py311`, `py312`)

-----

### CODE REVIEW

**Comment by lengau** [comment]
Thanks for making this @codethulu! I think we're in the same situation here [that we are for Charmcraft](https://github.com/canonical/charmcraft/pull/1626) - the workflow itself doesn't strictly care whether it's self-hosted or not, just that the runner has spread.

@sergiusens I believe the upcoming changes to the self-hosted runners for noble, arm64, etc. will affect this, so we'll probably need to do the same spread runner stuff here as we did for Charmcraft. ([Announcement](https://chat.canonical.com/canonical/pl/ugi4zhmmwfgy9dgarzq9q9bosh))

**Comment by sergiusens** [comment]
yeah, we want something like https://github.com/canonical/charmcraft/pull/1628/files and I would need to tag our runners that were deployed with spread

**Comment by lengau** [comment]
@sergiusens I've made a PR here and for Rockcraft:

* [Here](https://github.com/canonical/snapcraft/pull/4715)
* [Rockcraft](https://github.com/canonical/rockcraft/pull/524)

I believe you'll need to adjust the runner tags, but I used the same tag as charmcraft (`spread-installed`) for consistency

**Comment by lengau** [comment]
Closing as superseded. but once again @codethulu I appreciate this PR since it got us going on all this!

**Comment by codethulu** [comment]
No worries! Thanks for the update

**Pull request closed without merging**
