### PR TITLE
fix: correctly set PIP_NO_BINARY

### PR DESCRIPTION
**Pull request by dariuszd21**
- [ ] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `tox run -m lint`?
- [ ] Have you successfully run `tox run -e test-py310`? (supported versions: `py39`, `py310`, `py311`, `py312`)

-----

### CODE REVIEW

**Review by mr-cal — COMMENTED** [review]
Interesting, was `:all` silently being ignored by pip?

**Comment by dariuszd21** [comment]
> Interesting, I guess `:all` was silently being ignored by pip?
> 
> Looks like the build time has gone from 5 minutes to 20 minutes.

I think it was treated as a package name :sweat_smile:.
Currently the problem is that underlying build is a single-core, and that's why it takes so long to create a package from sources.
And maybe this could fix the `RISC-V` built :thinking:

**Comment by mr-cal** [comment]
This should start passing once https://github.com/canonical/craft-store/pull/221 is pulled in.

**Comment by mr-cal** [comment]
Closing because this was cherry-picked in https://github.com/canonical/snapcraft/pull/5084.  Thanks!

**Pull request closed without merging**
