### PR TITLE
Activate installed_base_by_architecture metrics

### PR DESCRIPTION
**Pull request by DanielDewberry**
Pursuant to my post on Discourse
(https://forum.snapcraft.io/t/enable-by-architecture-in-the-snapcraft-metrics-cli-tooling/39750), this commit activates the installed_base_by_architecture and weekly_installed_base_by_architecture metrics in the snapcraft metrics tool.

The metric was previously introduced according to this PR https://github.com/canonical/snapcraft.io/issues/1680#issuecomment-688928336

A subsequent issue will be raised against the documentation.

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `tox run -m lint`?
- [x] Have you successfully run `tox run -e test-py310`? (supported versions: `py39`, `py310`, `py311`, `py312`)

-----

### CODE REVIEW

**Comment by DanielDewberry** [comment]
I signed the CLA last night with the email address on my Snapcraft account.
I've just signed it again with the email on the commits. My Launchpad & Snapcraft accounts are dwd-daniel

**Comment by mr-cal** [comment]
PS - I just added these to [this](https://snapcraft.io/docs/snapcraft-metrics) documentation page

**Comment by DanielDewberry** [comment]
> Works great, thanks for the contribution!

Thank you very much :)

> PS - I just added these to [this](https://snapcraft.io/docs/snapcraft-metrics) documentation page

Thank you, that's great!

**Comment by DanielDewberry** [comment]
@mr-cal How should we proceed with regard to the failing CLA check? I have signed it with both the email address on the commit and the email address on my Launchpad account.

**Comment by mr-cal** [comment]
```
Checking the following users on GitHub:
Check in the signed list service
Error occurred while checking user: Request failed with status code 404
```

It looks like this problem with the github action: https://github.com/canonical/has-signed-canonical-cla/issues/37.

@sergiusens - How should we proceed?

**Comment by sergiusens** [comment]
The 404 is a result of the query. This should be fine to merge in anyways without waiting. but we can retry later and if it does not work I can go and track the systems responsible for the data.

**Review by sergiusens — APPROVED** [review]

**Comment by DanielDewberry** [comment]
Thank you both

**Comment by DanielDewberry** [comment]
> The 404 is a result of the query. This should be fine to merge in anyways without waiting. but we can retry later and if it does not work I can go and track the systems responsible for the data.

@mr-cal @sergiusens Do you need me to do/confirm anything?

**Comment by mr-cal** [comment]
@sergiusens - Can you override and merge?

**Comment by mr-cal** [comment]
Override-merging because CLA has been signed.

**Pull request merged**
