### PR TITLE
chore: move gnome-extension to stable

### PR DESCRIPTION
**Pull request by jssotomdz**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `tox run -m lint`?
- [x] Have you successfully run `tox run -e test-py310`? (supported versions: `py39`, `py310`, `py311`, `py312`)

-----

This PR will have to wait for the support for streamlined graphics as stated by #4736
We want to have it ready for that so we can start migrating desktop snaps to core24 when that is done

### CODE REVIEW

**Comment by jssotomdz** [comment]
@kenvandine

**Review by kenvandine — APPROVED** [review]
Looks good to me

**Comment by nteodosio** [comment]
I'm very interested in this as Chromium Dev now requires a new enough version of Pipewire not available in core22 and the alternative of building Pipewire from source is not so nice.

**Review by mr-cal — CHANGES_REQUESTED** [review]
@jssotomdz, can you drop the changes to `snapcraft/services/provider.py` and `tests/unit/services/test_provider.py`?

That code is not specific to the gnome extension, it's generic code for any experimental extension.

**Comment by jssotomdz** [comment]
> can you drop the changes to `snapcraft/services/provider.py` and `tests/unit/services/test_provider.py`?

done!

**Review by mr-cal — APPROVED** [review]

**Review by mattculler — APPROVED** [review]

**Pull request merged**
